import { IncidentRecord } from '../types/incident';

export const INITIAL_FORM_DATA: IncidentRecord = {
  incidentType: '',
  date: '',
  time: '',
  entryExit: '',
  nationality: '',
  gender: '',
  age: '',
  reason: '',
  overstayDays: '',
  penalty: '',
  banTime: '',
  carColor: '',
  carType: '',
  carOld: '',
  carRegisteredCountry: '',
  docuType: '',
  whatGoods: '',
  amountGoods: '',
  whereFounded: '',
  parensOld: '',
  parentGender: '',
  seizingCountry: 'ROU',
  otherDetails: '',
};

export const INCIDENT_TYPES = [
  'Hit in Database',
  'Refusal of Entry',
  'Overstay',
  'Administrative',
  'Asylum Request',
  'Avoiding Border Control',
  'Document Fraud',
  'FTF Suspicious Travel',
  'Hiding in Transportation Means/Clandestine',
  'Hit in Database – related to Terrorist / Extremist activities',
  'Illegal Border- Crossing',
  'Readmission',
  'Smuggling of goods',
  'Stolen Vehicles',
  'Trafficking in Human Beings',
  'Other',
];
